In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as se

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)

In [3]:
df = pd.read_csv("ohe_data_reduce_cat_class.csv")
df.shape

(7120, 108)

In [4]:
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Haralur Road  location_Raja Rajeshwari Nagar  \
0                      0                               0   
1                      0                               0   
2                      0                               0   
3                      0                               0   
4                      0                               0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_Yelahanka  location_7th Phase JP Nagar  location_Kanakpura Road  \
0                   0                            0                        0   
1                   0                            0                        0   
2                   0                            0                        0   
3                   0                            0                        0   
4                   0                            0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Bellandur  location_Kasavanhalli  location_Begur Road  \
0                   0                      0                    0   
1               

In [5]:
X = df.drop('price',axis = 1)
y = df['price']


In [6]:
print(X.shape)
print(y.shape)

(7120, 107)
(7120,)


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [8]:
X_train.head()

bath  balcony  total_sqft_int  bhk  price_per_sqft  \
2191   2.0      2.0          1550.0    3     5290.322581   
3289   3.0      3.0          1650.0    3    13333.333333   
2077   2.0      1.0          1000.0    2     2500.000000   
443    2.0      1.0           900.0    2     6666.666667   
2812   2.0      1.0          1285.0    2     4669.260700   

      area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
2191                              1                        0   
3289                              0                        1   
2077                              1                        0   
443                               0                        0   
2812                              1                        0   

      area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
2191                    0                           1                    0   
3289                    0                           1                    0   
2077                    0                           0                    0   
443                     0                           1                    0   
2812                    0                           1                    0   

      location_Sarjapur  Road  location_Electronic City  \
2191                        0                         0   
3289                        0                         0   
2077                        0                         0   
443                         0                         0   
2812                        0                         0   

      location_Marathahalli  location_Haralur Road  \
2191                      0                      0   
3289                      0                      0   
2077                      0                      0   
443                       0                      0   
2812                      0                      0   

      location_Raja Rajeshwari Nagar  location_Hennur Road  \
2191                               0                     0   
3289                               0                     0   
2077                               0                     0   
443                                0                     0   
2812                               0                     0   

      location_Bannerghatta Road  location_Uttarahalli  location_Thanisandra  \
2191                           0                     0                     0   
3289                           0                     0                     0   
2077                           0                     0                     0   
443                            0                     0                     0   
2812                           0                     0                     0   

      location_Electronic City Phase II  location_Hebbal  location_Yelahanka  \
2191                                  0                0                   0   
3289                                  0                0                   0   
2077                                  1                0                   0   
443                                   0                0                   0   
2812                                  0                0                   0   

      location_7th Phase JP Nagar  location_Kanakpura Road  location_KR Puram  \
2191                            0                        0                  0   
3289                            0                        0                  0   
2077                            0                        0                  0   
443                             0                        0                  0   
2812                            0                        0                  0   

      location_Sarjapur  location_Rajaji Nagar  location_Bellandur  \
2191                  0                      0                   0   
3289                  0                      0                   0   
2077                  0                      0                   0   
443      

In [9]:
X_train.shape

(5696, 107)

In [10]:
X_test.shape

(1424, 107)

## Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)

X_train = sc.transform(X_train)
X_test = sc.transform(X_test)

## Machine learning model training - Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

lr = LinearRegression()
L = Lasso()
R = Ridge()


In [13]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
def rmse(y_test, y_pred):
    return np.sqrt(mean_squared_error(y_test, y_pred))

In [38]:
lr_score = lr.score(X_train, y_train)
lr_rmse = rmse(y_test, lr.predict(X_test))

lr_score, lr_rmse

(0.8439925248308796, 30.197280464861294)

In [39]:
from  sklearn.model_selection import cross_val_score
cvc_lr = cross_val_score(LinearRegression(), X_train, y_train, cv = 10)

In [40]:
cvc_lr, cvc_lr.mean()

(array([0.78669553, 0.8433005 , 0.90009934, 0.90615692, 0.88341067,
        0.75505268, 0.89133185, 0.87153045, 0.86051494, 0.75662288]),
 0.8454715759153304)

In [41]:
##Lasso
L.fit(X_train, y_train)
lasso_score = L.score(X_train, y_train)
lasso_rmse = rmse(y_test, L.predict(X_test))

lasso_score, lasso_rmse

(0.8379453005868055, 32.03662850207261)

In [42]:
cvc_lasso = cross_val_score(L, X_train, y_train, cv = 10)
cvc_lasso

array([0.79697806, 0.85147744, 0.91435432, 0.91242607, 0.87868776,
       0.73258061, 0.89598462, 0.8674097 , 0.84677851, 0.74386637])

In [43]:
cvc_lasso.mean()

0.8440543467617212

## Support Vector machine

In [21]:
from sklearn.svm import SVR
svr = SVR()

In [44]:
svr.fit(X_train, y_train)
svr_score = svr.score(X_train, y_train)
svr_rmse = rmse(y_test, svr.predict(X_test))
svr_score, svr_rmse

(0.23850411699277507, 84.04637751054351)

## Random Forrest Regressor

In [45]:
from sklearn.ensemble import RandomForestRegressor
rfr = RandomForestRegressor()

rfr.fit(X_train,y_train)
rfr_score = rfr.score(X_train,y_train)
rfr_rmse = rmse(y_test, rfr.predict(X_test))

rfr_score, rfr_rmse

E:\ajeet_data\conda\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


(0.9808763547655297, 20.845299520306543)

In [46]:
cvc_rf = cross_val_score(rfr, X_train, y_train, cv = 10)

In [47]:
cvc_rf, cvc_rf.mean()

(array([0.99178477, 0.84900317, 0.97406659, 0.98890534, 0.99501687,
        0.94947514, 0.87086857, 0.99607005, 0.9825808 , 0.81389154]),
 0.9411662833638236)

## xgboost

In [24]:
import xgboost

In [25]:
xgb_reg = xgboost.XGBRegressor()
xgb_reg.fit(X_train, y_train)
xgb_reg_score = xgb_reg.score(X_test, y_test)
xgb_rmse_score = rmse(y_test, xgb_reg.predict(X_test))

xgb_reg_score, xgb_rmse_score

E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:19] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


(0.9748288551995413, 16.90478553091704)

In [26]:
xgb_cross = cross_val_score(xgb_reg, X_train, y_train, cv = 10)
xgb_cross, xgb_cross.mean()

E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:21] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:22] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:24] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:25] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:27] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:28] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:30] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:32] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:33] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:35] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


(array([0.97238291, 0.92297305, 0.99148215, 0.99307609, 0.97539016,
        0.97412628, 0.97328865, 0.99537308, 0.99096479, 0.86396011]),
 0.9653017244381991)

In [27]:
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBRegressor

In [28]:
xgb_tune2 =  XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=0.9, colsample_bytree=1, gamma=0,
             importance_type='gain', learning_rate=0.03, max_delta_step=0,
             max_depth=4, min_child_weight=5, missing=None, n_estimators=100,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=None, subsample=1, verbosity=1)
xgb_tune2.fit(X_train,y_train) 
xgb_tune2.score(X_test,y_test)

E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:37] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


0.9377564203963339

In [29]:
cvs = cross_val_score(xgb_tune2, X_train,y_train, cv = 5)
cvs, cvs.mean()

E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:39] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:40] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:42] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:43] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


E:\ajeet_data\conda\lib\site-packages\xgboost\core.py:587: FutureWarning: Series.base is deprecated and will be removed in a future version
  if getattr(data, 'base', None) is not None and \


[14:51:45] WARNING: src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.


(array([0.93697133, 0.95881285, 0.93690794, 0.9060984 , 0.83518916]),
 0.9147959378534811)

In [30]:
np.sqrt(mean_squared_error(y_test, xgb_tune2.predict(X_test)))

26.583090003845168

## Test model

In [31]:
list(X.columns)

['bath',
 'balcony',
 'total_sqft_int',
 'bhk',
 'price_per_sqft',
 'area_typeSuper built-up  Area',
 'area_typeBuilt-up  Area',
 'area_typePlot  Area',
 'availability_Ready To Move',
 'location_Whitefield',
 'location_Sarjapur  Road',
 'location_Electronic City',
 'location_Marathahalli',
 'location_Haralur Road',
 'location_Raja Rajeshwari Nagar',
 'location_Hennur Road',
 'location_Bannerghatta Road',
 'location_Uttarahalli',
 'location_Thanisandra',
 'location_Electronic City Phase II',
 'location_Hebbal',
 'location_Yelahanka',
 'location_7th Phase JP Nagar',
 'location_Kanakpura Road',
 'location_KR Puram',
 'location_Sarjapur',
 'location_Rajaji Nagar',
 'location_Bellandur',
 'location_Kasavanhalli',
 'location_Begur Road',
 'location_Banashankari',
 'location_Kothanur',
 'location_Hormavu',
 'location_Harlur',
 'location_Akshaya Nagar',
 'location_Jakkur',
 'location_Electronics City Phase 1',
 'location_Varthur',
 'location_Ramamurthy Nagar',
 'location_HSR Layout',
 'locatio

In [32]:
def predict_house_price(model,bath,balcony,total_sqft_int,bhk_size,price_per_sqft,area_type,availability,location):
    x = np.zeros(len(X.columns))
    
    #adding feature values according to their index
    x[0] = bath
    x[1] = balcony
    x[3] = total_sqft_int
    x[4] = bhk_size
    x[5] = price_per_sqft
    
    if "availability" == "Ready To Move":
            x[8] = 1
    
    if 'area_type' +area_type in X.columns:
        area_type_index = np.where(X.columns == 'area_type'+area_type)[0][0]
        x[area_type_index] = 1
        
    
    if 'location'+location in X.columns:
        loc_index = np.where(X.columns == 'location'+location)[0][0]
        x[loc_index] = 1
    
    x = sc.transform([x])[0]
    
    return model.predict([x])[0]
    
    
    

In [33]:
predict_house_price(model=xgb_tune2, bath=3,balcony=2,total_sqft_int=1672,bhk_size=3,price_per_sqft=8971.291866,area_type="Plot  Area",availability="Ready To Move",location="Devarabeesana Halli")

25.426348

In [34]:
predict_house_price(model=xgb_tune2, bath=3,balcony=2,total_sqft_int=1750,bhk_size=3,price_per_sqft=8571.428571,area_type="Super built-up",availability="Ready To Move",location="Devarabeesana Halli")

25.426348

In [35]:
X.head()

bath  balcony  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0          1672.0    3     8971.291866   
1   3.0      3.0          1750.0    3     8514.285714   
2   3.0      2.0          1750.0    3     8571.428571   
3   2.0      2.0          1250.0    2     3200.000000   
4   2.0      2.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
0                    0                           1                    0   
1                    0                           1                    0   
2                    0                           1                    0   
3                    0                           1                    0   
4                    1                           1                    0   

   location_Sarjapur  Road  location_Electronic City  location_Marathahalli  \
0                        0                         0                      0   
1                        0                         0                      0   
2                        0                         0                      0   
3                        0                         0                      0   
4                        0                         0                      0   

   location_Haralur Road  location_Raja Rajeshwari Nagar  \
0                      0                               0   
1                      0                               0   
2                      0                               0   
3                      0                               0   
4                      0                               0   

   location_Hennur Road  location_Bannerghatta Road  location_Uttarahalli  \
0                     0                           0                     0   
1                     0                           0                     0   
2                     0                           0                     0   
3                     0                           0                     0   
4                     0                           0                     0   

   location_Thanisandra  location_Electronic City Phase II  location_Hebbal  \
0                     0                                  0                0   
1                     0                                  0                0   
2                     0                                  0                0   
3                     0                                  0                0   
4                     0                                  0                0   

   location_Yelahanka  location_7th Phase JP Nagar  location_Kanakpura Road  \
0                   0                            0                        0   
1                   0                            0                        0   
2                   0                            0                        0   
3                   0                            0                        0   
4                   0                            0                        0   

   location_KR Puram  location_Sarjapur  location_Rajaji Nagar  \
0                  0                  0                      0   
1                  0                  0                      0   
2                  0                  0                      0   
3                  0                  0                      0   
4                  0                  0                      0   

   location_Bellandur  location_Kasavanhalli  location_Begur Road  \
0                   0                      0                    0   
1                   0                      0              

In [36]:
predict_house_price(model=rfr, bath=3,balcony=2,total_sqft_int=1200.0,bhk_size=2,price_per_sqft=6916.666667,area_type="Plot Area",availability="Ready To Move",location="Whitefield")

10.481

In [37]:
y.head()

0    150.0
1    149.0
2    150.0
3     40.0
4     83.0
Name: price, dtype: float64